version: "3.2"
services:
  code:
    container_name: code
    image: darrentsung/docker-amethyst-rust:1.29
    stdin_open: true
    tty: true
    command: bash
    working_dir: /code
    volumes:
      - .:/code:cached
      - target:/code/target
      - cargo:/usr/local/cargo

volumes:
  target:
  cargo:
